const COMPANY_TO_TICKER = {
  'international business machines corporation': 'IBM',
  'american electric power company inc ': 'AEP',
  'norwegian cruise line holdings ltd ': 'NCLH',
  'vertex pharmaceuticals incorporated': 'VRTX',
  'take two interactive software inc ': 'TTWO',
  'american international group inc ': 'AIG',
  'occidental petroleum corporation': 'OXY',
  'philip morris international inc ': 'PM',
  'air products and chemicals inc ': 'APD',
  'international business machines': 'IBM',
  'unitedhealth group incorporated': 'UNH',
  'hilton worldwide holdings inc ': 'HLT',
  'intercontinental exchange inc ': 'ICE',
  'marathon petroleum corporation': 'MPC',
  'regeneron pharmaceuticals inc ': 'REGN',
  'texas instruments incorporated': 'TXN',
  'the charles schwab corporation': 'SCHW',
  'alpha and omega semiconductor': 'AOSL',
  'boston scientific corporation': 'BSX',
  'marsh mclennan companies inc ': 'MMC',
  'sherwin williams company the ': 'SHW',
  'take two interactive software': 'TTWO',
  'thermo fisher scientific inc ': 'TMO',
  'united airlines holdings inc ': 'UAL',
  'american airlines group inc ': 'AAL',
  'bristol myers squibb company': 'BMY',
  'costco wholesale corporation': 'COST',
  'general dynamics corporation': 'GD',
  'honeywell international inc ': 'HON',
  'northrop grumman corporation': 'NOC',
  'royal caribbean cruises ltd ': 'RCL',
  'sherwin williams company the': 'SHW',
  'the goldman sachs group inc ': 'GS',
  'the travelers companies inc ': 'TRV',
  'advanced micro devices inc ': 'AMD',
  'bank of america corporation': 'BAC',
  'berkshire hathaway class b ': 'BRK-B',
  'cadence design systems inc ': 'CDNS',
  'chipotle mexican grill inc ': 'CMG',
  'lockheed martin corporation': 'LMT',
  'marriott international inc ': 'MAR',
  'national storage affiliates': 'NSA',
  'philip morris international': 'PM',
  'verizon communications inc ': 'VZ',
  'williams companies inc the ': 'WMB',
  'air products and chemicals': 'APD',
  'berkshire hathaway class b': 'BRK-B',
  'dollar general corporation': 'DG',
  'hewlett packard enterprise': 'HPE',
  'national retail properties': 'NNN',
  'palantir technologies inc ': 'PLTR',
  'williams companies inc the': 'WMB',
  'crowdstrike holdings inc ': 'CRWD',
  'intercontinental exchange': 'ICE',
  'pioneer natural resources': 'PXD',
  'prudential financial inc ': 'PRU',
  'public service enterprise': 'PEG',
  'regeneron pharmaceuticals': 'REGN',
  'union pacific corporation': 'UNP',
  'american express company': 'AXP',
  'general electric company': 'GE',
  'lam research corporation': 'LRCX',
  'marsh mclennan companies': 'MMC',
  'sherwin williams company': 'SHW',
  'sherwin williamspany the': 'SHW',
  'the allstate corporation': 'ALL',
  'thermo fisher scientific': 'TMO',
  'walt disney company the ': 'DIS',
  'american electric power': 'AEP',
  'duke energy corporation': 'DUK',
  'exxon mobil corporation': 'XOM',
  'honeywell international': 'HON',
  'intercontinental hotels': 'IHG',
  'intuitive surgical inc ': 'ISRG',
  'marvell technology inc ': 'MRVL',
  'mastercard incorporated': 'MA',
  'motorola solutions inc ': 'MSI',
  'palo alto networks inc ': 'PANW',
  'progressive corporation': 'PGR',
  'royal caribbean cruises': 'RCL',
  'the travelers companies': 'TRV',
  'walt disney company the': 'DIS',
  'williams companies inc ': 'WMB',
  'advanced micro devices': 'AMD',
  'american international': 'AIG',
  'applied materials inc ': 'AMAT',
  'cadence design systems': 'CDNS',
  'chipotle mexican grill': 'CMG',
  'coca cola company the ': 'KO',
  'cvs health corporation': 'CVS',
  'general motors company': 'GM',
  'hilton grand vacations': 'HGV',
  'marriott international': 'MAR',
  'mcdonald s corporation': 'MCD',
  'micron technology inc ': 'MU',
  'ollie s bargain outlet': 'OLLI',
  'uber technologies inc ': 'UBER',
  'verizon communications': 'VZ',
  'vertex pharmaceuticals': 'VRTX',
  'williamspanies inc the': 'WMB',
  'alphabet inc class a ': 'GOOGL',
  'alphabet inc class c ': 'GOOG',
  'booking holdings inc ': 'BKNG',
  'coca cola company the': 'KO',
  'continental resources': 'CLR',
  'eli lilly and company': 'LLY',
  'freeport mcmoran inc ': 'FCX',
  'huntington bancshares': 'HBAN',
  'lowe s companies inc ': 'LOW',
  'madison square garden': 'MSG',
  'microsoft corporation': 'MSFT',
  'mid america apartment': 'MAA',
  'norwegian cruise line': 'NCLH',
  'palantir technologies': 'PLTR',
  'qualcomm incorporated': 'QCOM',
  'starbucks corporation': 'SBUX',
  'warner bros discovery': 'WBD',
  'allegro microsystems': 'ALGM',
  'allison transmission': 'ALSN',
  'alphabet inc class a': 'GOOGL',
  'alphabet inc class c': 'GOOG',
  'american water works': 'AWK',
  'axcelis technologies': 'ACLS',
  'bristol myers squibb': 'BMY',
  'cincinnati financial': 'CINF',
  'constellation brands': 'STZ',
  'delta air lines inc ': 'DAL',
  'dicks sporting goods': 'DKS',
  'dominion energy inc ': 'D',
  'edison international': 'EIX',
  'electronic arts inc ': 'EA',
  'gilead sciences inc ': 'GILD',
  'horizon therapeutics': 'HZNP',
  'jazz pharmaceuticals': 'JAZZ',
  'manhattan associates': 'MANH',
  'marsh mclennanpanies': 'MMC',
  'microchip technology': 'MCHP',
  'occidental petroleum': 'OXY',
  'paypal holdings inc ': 'PYPL',
  'prudential financial': 'PRU',
  'restoration hardware': 'RH',
  'schlumberger limited': 'SLB',
  'stanley black decker': 'SWK',
  'taiwan semiconductor': 'TSM',
  'the southern company': 'SO',
  'ultra clean holdings': 'UCTT',
  'united natural foods': 'UNFI',
  'willis towers watson': 'WTW',
  'zions bancorporation': 'ZION',
  'activision blizzard': 'ATVI',
  'affiliated managers': 'AMG',
  'analog devices inc ': 'ADI',
  'ashford hospitality': 'AHT',
  'blueprint medicines': 'BPMC',
  'boeing company the ': 'BA',
  'chevron corporation': 'CVX',
  'comcast corporation': 'CMCSA',
  'consolidated edison': 'ED',
  'danaher corporation': 'DHR',
  'essential utilities': 'WTR',
  'extra space storage': 'EXR',
  'federated investors': 'FII',
  'illinois tool works': 'ITW',
  'johnson and johnson': 'JNJ',
  'kroger company the ': 'KR',
  'meta platforms inc ': 'META',
  'moody s corporation': 'MCO',
  'newmont corporation': 'NEM',
  'nextera energy inc ': 'NEE',
  'rockwell automation': 'ROK',
  'ross dress for less': 'ROST',
  'southwestern energy': 'SWN',
  'stryker corporation': 'SYK',
  'the travelerspanies': 'TRV',
  'united therapeutics': 'UTHR',
  'wall street journal': 'NWSA',
  'walt disney company': 'DIS',
  'walt disneypany the': 'DIS',
  'wells fargo company': 'WFC',
  'arthur j gallagher': 'AJG',
  'berkshire hathaway': 'BRK-B',
  'blade air mobility': 'BLDE',
  'boeing company the': 'BA',
  'cisco systems inc ': 'CSCO',
  'citizens financial': 'CFG',
  'diamondback energy': 'FANG',
  'eog resources inc ': 'EOG',
  'equity residential': 'EQR',
  'exelon corporation': 'EXC',
  'ford motor company': 'F',
  'franklin templeton': 'BEN',
  'huntington ingalls': 'HII',
  'intuitive machines': 'LUNR',
  'intuitive surgical': 'ISRG',
  'jpmorgan chase co ': 'JPM',
  'kinder morgan inc ': 'KMI',
  'kroger company the': 'KR',
  'marathon petroleum': 'MPC',
  'marvell technology': 'MRVL',
  'motorola solutions': 'MSI',
  'nvidia corporation': 'NVDA',
  'nxp semiconductors': 'NXPI',
  'oracle corporation': 'ORCL',
  'palo alto networks': 'PANW',
  'penn entertainment': 'PENN',
  'sba communications': 'SBAC',
  'service properties': 'SVC',
  'southwest airlines': 'LUV',
  'stmicroelectronics': 'STM',
  'target corporation': 'TGT',
  'the charles schwab': 'SCHW',
  'verizonmunications': 'VZ',
  'vertical aerospace': 'EVTL',
  'williams companies': 'WMB',
  'alliancebernstein': 'AB',
  'altria group inc ': 'MO',
  'american airlines': 'AAL',
  'american electric': 'AEP',
  'applied materials': 'AMAT',
  'boston scientific': 'BSX',
  'british petroleum': 'BP',
  'chesapeake energy': 'CHK',
  'coca cola company': 'KO',
  'coca colapany the': 'KO',
  'colgate palmolive': 'CL',
  'frontier airlines': 'ULCC',
  'hawaiian airlines': 'HA',
  'intel corporation': 'INTC',
  'marathon holdings': 'MARA',
  'matador resources': 'MTDR',
  'micron technology': 'MU',
  'msg entertainment': 'MSGE',
  'purple innovation': 'PRPL',
  'restaurant brands': 'QSR',
  'royal dutch shell': 'SHEL',
  'texas instruments': 'TXN',
  'the goldman sachs': 'GS',
  'uber technologies': 'UBER',
  'victoria s secret': 'VSCO',
  'american express': 'AXP',
  'antero resources': 'AR',
  'bank of new york': 'BK',
  'california water': 'CWT',
  'callon petroleum': 'CPE',
  'caterpillar inc ': 'CAT',
  'cigna group the ': 'CI',
  'costco wholesale': 'COST',
  'dave and busters': 'PLAY',
  'dollar tree inc ': 'DLTR',
  'equity lifestyle': 'ELS',
  'federated hermes': 'FHI',
  'freeport mcmoran': 'FCX',
  'general dynamics': 'GD',
  'general electric': 'GE',
  'hilton worldwide': 'HLT',
  'invitation homes': 'INVH',
  'keurig dr pepper': 'KDP',
  'lincoln national': 'LNC',
  'lowe s companies': 'LOW',
  'marathon digital': 'MARA',
  'monolithic power': 'MPWR',
  'monster beverage': 'MNST',
  'northrop grumman': 'NOC',
  'on semiconductor': 'ON',
  'rocket companies': 'RKT',
  'sherwin williams': 'SHW',
  'southern company': 'SO',
  't mobile us inc ': 'TMUS',
  'urban outfitters': 'URBN',
  'volatility index': 'VIX',
  'alaska airlines': 'ALK',
  'amazon com inc ': 'AMZN',
  'apa corporation': 'APA',
  'archer aviation': 'ACHR',
  'ares management': 'ARES',
  'ast spacemobile': 'ASTS',
  'bank of america': 'BAC',
  'bath body works': 'BBWI',
  'bed bath beyond': 'BBBY',
  'camden property': 'CPT',
  'chatham lodging': 'CLDT',
  'cigna group the': 'CI',
  'cloudflare inc ': 'NET',
  'daqo new energy': 'DQ',
  'delta air lines': 'DAL',
  'dominion energy': 'D',
  'electronic arts': 'EA',
  'eqt corporation': 'EQT',
  'fox corporation': 'FOXA',
  'fuelcell energy': 'FCEL',
  'gilead sciences': 'GILD',
  'ginkgo bioworks': 'DNA',
  'glaxosmithkline': 'GSK',
  'global payments': 'GPN',
  'gray television': 'GTN',
  'jack in the box': 'JACK',
  'janus henderson': 'JHG',
  'johnson johnson': 'JNJ',
  'kla corporation': 'KLAC',
  'las vegas sands': 'LVS',
  'lockheed martin': 'LMT',
  'parker hannifin': 'PH',
  'pilgrim s pride': 'PPC',
  'range resources': 'RRC',
  'rent the runway': 'RENT',
  'riot blockchain': 'RIOT',
  'rocket mortgage': 'RKT',
  'royal caribbean': 'RCL',
  'rtx corporation': 'RTX',
  's p global inc ': 'SPGI',
  'salesforce inc ': 'CRM',
  'sanderson farms': 'SAFM',
  'sei investments': 'SEIC',
  'servicenow inc ': 'NOW',
  'spirit airlines': 'SAVE',
  'sun communities': 'SUI',
  'te connectivity': 'TEL',
  'texas roadhouse': 'TXRH',
  'united airlines': 'UAL',
  'vici properties': 'VICI',
  'victory capital': 'VCTR',
  'virgin galactic': 'SPCE',
  'williams sonoma': 'WSM',
  'yum brands inc ': 'YUM',
  'academy sports': 'ASO',
  'ally financial': 'ALLY',
  'american eagle': 'AEO',
  'american homes': 'AMH',
  'american tower': 'AMT',
  'analog devices': 'ADI',
  'anheuser busch': 'BUD',
  'ark innovation': 'ARKK',
  'bj s wholesale': 'BJ',
  'blackrock inc ': 'BLK',
  'blink charging': 'BLNK',
  'boeing company': 'BA',
  'boeingpany the': 'BA',
  'canadian solar': 'CSIQ',
  'charles schwab': 'SCHW',
  'citigroup inc ': 'C',
  'cme group inc ': 'CME',
  'cnh industrial': 'CNHI',
  'conocophillips': 'COP',
  'delta airlines': 'DAL',
  'digital realty': 'DLR',
  'dollar general': 'DG',
  'domino s pizza': 'DPZ',
  'essex property': 'ESS',
  'faraday future': 'FFIE',
  'general motors': 'GM',
  'guild holdings': 'GHLD',
  'johnnie walker': 'DEO',
  'jpmorgan chase': 'JPM',
  'kimberly clark': 'KMB',
  'kroger company': 'KR',
  'krogerpany the': 'KR',
  'marsh mclennan': 'MMC',
  'meta platforms': 'META',
  'michael saylor': 'MSTR',
  'monster energy': 'MNST',
  'morgan stanley': 'MS',
  'new york times': 'NYT',
  'nextera energy': 'NEE',
  'northern trust': 'NTRS',
  'procter gamble': 'PG',
  'public storage': 'PSA',
  'ree automotive': 'REE',
  'riot platforms': 'RIOT',
  'rockstar games': 'TTWO',
  'silicon motion': 'SIMO',
  'simon property': 'SPG',
  'terran orbital': 'LLAP',
  'the home depot': 'HD',
  'travel leisure': 'TNL',
  'unity software': 'U',
  'vf corporation': 'VFC',
  'warren buffett': 'BRK-B',
  'accenture plc': 'ACN',
  'alphabet inc ': 'GOOG',
  'america movil': 'AMX',
  'ballard power': 'BLDP',
  'beauty health': 'SKIN',
  'bill holdings': 'BILL',
  'bristol myers': 'BMY',
  'broadcom inc ': 'AVGO',
  'campbell soup': 'CPB',
  'choice hotels': 'CHH',
  'chubb limited': 'CB',
  'church dwight': 'CHD',
  'cipher mining': 'CIFR',
  'cisco systems': 'CSCO',
  'cna financial': 'CNA',
  'deere company': 'DE',
  'elf cosmetics': 'ELF',
  'eli lilly and': 'LLY',
  'eog resources': 'EOG',
  'fortinet inc ': 'FTNT',
  'freyr battery': 'FREY',
  'general mills': 'GIS',
  'golden nugget': 'GNOG',
  'goldman sachs': 'GS',
  'inter parfums': 'IPAR',
  'joby aviation': 'JOBY',
  'kinder morgan': 'KMI',
  'liberty media': 'FWONK',
  'medtronic plc': 'MDT',
  'merck co inc ': 'MRK',
  'mesa airlines': 'MESA',
  'microstrategy': 'MSTR',
  'philip morris': 'PM',
  'quicken loans': 'RKT',
  'realty income': 'O',
  'renaissancere': 'RNR',
  'shoe carnival': 'SCVL',
  'synopsys inc ': 'SNPS',
  'tencent music': 'TME',
  'thermo fisher': 'TMO',
  'totalenergies': 'TTE',
  'union pacific': 'UNP',
  'western union': 'WU',
  'ark genomics': 'ARKG',
  'arm holdings': 'ARM',
  'baker hughes': 'BKR',
  'bloom energy': 'BE',
  'bluebird bio': 'BLUE',
  'brown forman': 'BF.A',
  'china mobile': 'CHL',
  'china unicom': 'CHU',
  'chord energy': 'CHRD',
  'cirrus logic': 'CRUS',
  'crown castle': 'CCI',
  'dave busters': 'PLAY',
  'devon energy': 'DVN',
  'e l f beauty': 'ELF',
  'estee lauder': 'EL',
  'jack daniels': 'BF.A',
  'jensen huang': 'NVDA',
  'lam research': 'LRCX',
  'life storage': 'LSI',
  'lowe spanies': 'LOW',
  'marathon oil': 'MRO',
  'mercadolibre': 'MELI',
  'metlife inc ': 'MET',
  'molson coors': 'TAP',
  'nbcuniversal': 'CMCSA',
  'netflix inc ': 'NFLX',
  'novo nordisk': 'NVO',
  'olive garden': 'DRI',
  'open lending': 'LPRO',
  'pepsico inc ': 'PEP',
  'playa hotels': 'PLYA',
  'quantumscape': 'QS',
  'ralph lauren': 'RL',
  'russell 2000': 'IWM',
  'samuel adams': 'SAM',
  'schlumberger': 'SLB',
  'silicon labs': 'SLAB',
  'spire global': 'SPIR',
  'state street': 'STT',
  't rowe price': 'TROW',
  'the allstate': 'ALL',
  'the southern': 'SO',
  'ticketmaster': 'LYV',
  'toro company': 'TTC',
  'total market': 'VTI',
  'u s cellular': 'USM',
  'under armour': 'UA',
  'unitedhealth': 'UNH',
  'uwm holdings': 'UWMC',
  'walmart inc ': 'WMT',
  'warner music': 'WMG',
  'xenia hotels': 'XHR',
  'zillow group': 'ZG',
  'zscaler inc ': 'ZS',
  'abbvie inc ': 'ABBV',
  'abercrombie': 'ANF',
  'airbnb inc ': 'ABNB',
  'astrazeneca': 'AZN',
  'booking com': 'BKNG',
  'boston beer': 'SAM',
  'brown brown': 'BRO',
  'burger king': 'QSR',
  'capital one': 'COF',
  'caterpillar': 'CAT',
  'cathie wood': 'ARKK',
  'centerpoint': 'CNP',
  'chargepoint': 'CHPT',
  'check point': 'CHKP',
  'cigna group': 'CI',
  'crowdstrike': 'CRWD',
  'diamondback': 'FANG',
  'diamondrock': 'DRH',
  'dollar tree': 'DLTR',
  'duke energy': 'DUK',
  'eaton vance': 'EV',
  'ecolab inc ': 'ECL',
  'exxon mobil': 'XOM',
  'fifth third': 'FITB',
  'first solar': 'FSLR',
  'firstenergy': 'FE',
  'foot locker': 'FL',
  'formula one': 'FWONK',
  'halliburton': 'HAL',
  'host hotels': 'HST',
  'humana inc ': 'HUM',
  'hydrafacial': 'SKIN',
  'intuit inc ': 'INTU',
  'j m smucker': 'SJM',
  'jamie dimon': 'JPM',
  'jinko solar': 'JKS',
  'lendingclub': 'LC',
  'lendingtree': 'TREE',
  'live nation': 'LYV',
  'match group': 'MTCH',
  'mgm resorts': 'MGM',
  'new holland': 'CNHI',
  'park hotels': 'PK',
  'pdce energy': 'PDCE',
  'pfizer inc ': 'PFE',
  'phillips 66': 'PSX',
  'progressive': 'PGR',
  'rlj lodging': 'RLJ',
  'ross stores': 'ROST',
  'rush street': 'RSI',
  'sea limited': 'SE',
  'sentinelone': 'S',
  'shake shack': 'SHAK',
  'super micro': 'SMCI',
  't mobile us': 'TMUS',
  'tim hortons': 'QSR',
  'tripadvisor': 'TRIP',
  'tyson foods': 'TSN',
  'ulta beauty': 'ULTA',
  'w r berkley': 'WRB',
  'walt disney': 'DIS',
  'warner bros': 'WBD',
  'wells fargo': 'WFC',
  'activision': 'ATVI',
  'adobe inc ': 'ADBE',
  'air france': 'AF',
  'alaska air': 'ALK',
  'albertsons': 'ACI',
  'amazon com': 'AMZN',
  'amgen inc ': 'AMGN',
  'apple inc ': 'AAPL',
  'arm hammer': 'CHD',
  'blackstone': 'BX',
  'bny mellon': 'BK',
  'borgwarner': 'BWA',
  'burlington': 'BURL',
  'campbell s': 'CPB',
  'cedar fair': 'FUN',
  'cleanspark': 'CLSK',
  'cloudflare': 'NET',
  'cms energy': 'CMS',
  'cvs health': 'CVS',
  'draftkings': 'DKNG',
  'dte energy': 'DTE',
  'everest re': 'RE',
  'eversource': 'ES',
  'exxonmobil': 'XOM',
  'fear index': 'VIX',
  'five below': 'FIVE',
  'ford motor': 'F',
  'formfactor': 'FORM',
  'globalstar': 'GSAT',
  'home depot': 'HD',
  'jack henry': 'JKHY',
  'john deere': 'DE',
  'larry fink': 'BLK',
  'mastercard': 'MA',
  'mcdonald s': 'MCD',
  'msg sports': 'MSGS',
  'nasdaq 100': 'QQQ',
  'neurocrine': 'NBIX',
  'north face': 'VFC',
  'occidental': 'OXY',
  'plug power': 'PLUG',
  'prudential': 'PRU',
  'quickbooks': 'INTU',
  'rocket lab': 'RKLB',
  's p global': 'SPGI',
  'salesforce': 'CRM',
  'servicenow': 'NOW',
  'shenandoah': 'SHEN',
  'stitch fix': 'SFIX',
  'supermicro': 'SMCI',
  'telefonica': 'TEF',
  'tesla inc ': 'TSLA',
  'trade desk': 'TTD',
  'ultragenyx': 'RARE',
  'us bancorp': 'USB',
  'wec energy': 'WEC',
  'yum brands': 'YUM',
  'zoom video': 'ZM',
  'accenture': 'ACN',
  'allegiant': 'ALGT',
  'ally bank': 'ALLY',
  'americold': 'COLD',
  'at t inc ': 'T',
  'atlassian': 'TEAM',
  'avalanche': 'AVAX-USD',
  'avalonbay': 'AVB',
  'berkshire': 'BRK-B',
  'blackrock': 'BLK',
  'budweiser': 'BUD',
  'cal maine': 'CALM',
  'chainlink': 'LINK-USD',
  'citigroup': 'C',
  'coca cola': 'KO',
  'confluent': 'CFLT',
  'cubesmart': 'CUBE',
  'dillard s': 'DDS',
  'discovery': 'WBD',
  'dow jones': 'DIA',
  'ea sports': 'EA',
  'eli lilly': 'LLY',
  'elon musk': 'TSLA',
  'h r block': 'HRB',
  'hims hers': 'HIMS',
  'honeywell': 'HON',
  'jp morgan': 'JPM',
  'kellanova': 'K',
  'linde plc': 'LIN',
  'lordstown': 'RIDE',
  'lufthansa': 'LHA',
  'lululemon': 'LULU',
  'marshalls': 'TJX',
  'mccormick': 'MKC',
  'mcdonalds': 'MCD',
  'medtronic': 'MDT',
  'microchip': 'MCHP',
  'microsoft': 'MSFT',
  'microvast': 'MVST',
  'news corp': 'NWSA',
  'nike inc ': 'NKE',
  'nordstrom': 'JWN',
  'palo alto': 'PANW',
  'paramount': 'PARA',
  'pinduoduo': 'PDD',
  'pinterest': 'PINS',
  'pizza hut': 'YUM',
  'priceline': 'BKNG',
  'recursion': 'RXRX',
  'regeneron': 'REGN',
  'rev group': 'REVG',
  'richemont': 'CFRUY',
  'robinhood': 'HOOD',
  'six flags': 'SIX',
  'sjw group': 'SJW',
  'sm energy': 'SM',
  'snowflake': 'SNOW',
  'solaredge': 'SEDG',
  'southwest': 'LUV',
  'starbucks': 'SBUX',
  'synchrony': 'SYF',
  'taco bell': 'YUM',
  'travelers': 'TRV',
  'usa today': 'GCI',
  'visa inc ': 'V',
  'w p carey': 'WPC',
  'wolfspeed': 'WOLF',
  'workhorse': 'WKHS',
  '2k games': 'TTWO',
  'ab inbev': 'BUD',
  'alkermes': 'ALKS',
  'allstate': 'ALL',
  'alphabet': 'GOOG',
  'amphenol': 'APH',
  'autodesk': 'ADSK',
  'barstool': 'PENN',
  'best buy': 'BBY',
  'bilibili': 'BILI',
  'bill com': 'BILL',
  'biomarin': 'BMRN',
  'biontech': 'BNTX',
  'bitfarms': 'BITF',
  'blue owl': 'OWL',
  'broadcom': 'AVGO',
  'cash app': 'SQ',
  'cheerios': 'GIS',
  'chipotle': 'CMG',
  'citibank': 'C',
  'coinbase': 'COIN',
  'comerica': 'CMA',
  'cyberark': 'CYBR',
  'dillards': 'DDS',
  'discover': 'DFS',
  'docusign': 'DOCU',
  'dogecoin': 'DOGE-USD',
  'dominion': 'D',
  'doordash': 'DASH',
  'endeavor': 'EDR',
  'ethereum': 'ETH-USD',
  'exelixis': 'EXEL',
  'facebook': 'META',
  'fleetcor': 'FLT',
  'fortinet': 'FTNT',
  'fox corp': 'FOX',
  'fox news': 'FOX',
  'freeport': 'FCX',
  'frontier': 'FYBR',
  'gamestop': 'GME',
  'gillette': 'PG',
  'global e': 'GLBE',
  'guinness': 'DEO',
  'hartford': 'HIG',
  'hawaiian': 'HA',
  'intellia': 'NTLA',
  'jingdong': 'JD',
  'jpmorgan': 'JPM',
  'keysight': 'KEYS',
  'leslie s': 'LESL',
  'litecoin': 'LTC-USD',
  'lockheed': 'LMT',
  'longhorn': 'DRI',
  'm t bank': 'MTB',
  'marriott': 'MAR',
  'mcdonald': 'MCD',
  'mimecast': 'MIME',
  'momentus': 'MNTS',
  'mondelez': 'MDLZ',
  'motorola': 'MSI',
  'nintendo': 'NTDOY',
  'northrop': 'NOC',
  'novartis': 'NVS',
  'opendoor': 'OPEN',
  'palantir': 'PLTR',
  'polkadot': 'DOT-USD',
  'prologis': 'PLD',
  'proterra': 'PTRA',
  'qualcomm': 'QCOM',
  'raytheon': 'RTX',
  'realreal': 'REAL',
  'rockstar': 'TTWO',
  'seaworld': 'SEAS',
  'sinclair': 'SBGI',
  'siriusxm': 'SIRI',
  'skyworks': 'SWKS',
  'smuckers': 'SJM',
  'snapchat': 'SNAP',
  'sunpower': 'SPWR',
  'sunstone': 'SHO',
  'synopsys': 'SNPS',
  't mobile': 'TMUS',
  'take two': 'TTWO',
  'turbotax': 'INTU',
  'vodafone': 'VOD',
  'wingstop': 'WING',
  'alibaba': 'BABA',
  'alnylam': 'ALNY',
  'aon plc': 'AON',
  'arrival': 'ARVL',
  'autoliv': 'ALV',
  'beigene': 'BGNE',
  'bitcoin': 'BTC-USD',
  'booking': 'BKNG',
  'brinker': 'EAT',
  'cadbury': 'MDLZ',
  'cadence': 'CDNS',
  'caesars': 'CZR',
  'cardano': 'ADA-USD',
  'carlyle': 'CG',
  'cartier': 'CFRUY',
  'carvana': 'CVNA',
  'case ih': 'CNHI',
  'casey s': 'CASY',
  'chevron': 'CVX',
  'chili s': 'EAT',
  'colgate': 'CL',
  'comcast': 'CMCSA',
  'compass': 'COMP',
  'conagra': 'CAG',
  'corning': 'GLW',
  'coterra': 'CTRA',
  'coupang': 'CPNG',
  'cummins': 'CMI',
  'danaher': 'DHR',
  'datadog': 'DDOG',
  'dominos': 'DPZ',
  'dropbox': 'DBX',
  'elastic': 'ESTC',
  'embraer': 'ERJ',
  'emerson': 'EMR',
  'enphase': 'ENPH',
  'entergy': 'ETR',
  'equinix': 'EQIX',
  'expedia': 'EXPE',
  'express': 'EXPR',
  'gannett': 'GCI',
  'generac': 'GNRC',
  'goldman': 'GS',
  'hershey': 'HSY',
  'hibbett': 'HIBB',
  'hubspot': 'HUBS',
  'huggies': 'KMB',
  'hyliion': 'HYLN',
  'invesco': 'IVZ',
  'iridium': 'IRDM',
  'jetblue': 'JBLU',
  'juniper': 'JNPR',
  'kellogg': 'K',
  'keybank': 'KEY',
  'keycorp': 'KEY',
  'kleenex': 'KMB',
  'li auto': 'LI',
  'lisa su': 'AMD',
  'lovesac': 'LOVE',
  'marvell': 'MRVL',
  'metlife': 'MET',
  'moderna': 'MRNA',
  'mongodb': 'MDB',
  'moody s': 'MCO',
  'netease': 'NTES',
  'netflix': 'NFLX',
  'newmont': 'NEM',
  'nextera': 'NEE',
  'novavax': 'NVAX',
  'nu skin': 'NUS',
  'oshkosh': 'OSK',
  'ovintiv': 'OVV',
  'peloton': 'PTON',
  'pepsico': 'PEP',
  'pioneer': 'PXD',
  'polygon': 'MATIC-USD',
  'popeyes': 'QSR',
  'red cat': 'RCAT',
  'regions': 'RF',
  'roivant': 'ROIV',
  'russell': 'IWM',
  'ryanair': 'RYAAY',
  's p 500': 'SPY',
  'sarepta': 'SRPT',
  'scripps': 'SSP',
  'shopify': 'SHOP',
  'skywest': 'SKYW',
  'spotify': 'SPOT',
  'sprouts': 'SFM',
  'stmicro': 'STM',
  'stryker': 'SYK',
  'sunnova': 'NOVA',
  'tenable': 'TENB',
  'tencent': 'TCEHY',
  'textron': 'TXT',
  'tiffany': 'TIF',
  'tj maxx': 'TJX',
  'tmobile': 'TMUS',
  'twitter': 'X',
  'uniswap': 'UNI-USD',
  'upstart': 'UPST',
  'us bank': 'USB',
  'vaxcyte': 'PCVX',
  'verizon': 'VZ',
  'visteon': 'VC',
  'walmart': 'WMT',
  'wayfair': 'W',
  'wendy s': 'WEN',
  'workday': 'WDAY',
  'wyndham': 'WH',
  'zendesk': 'ZEN',
  'zscaler': 'ZS',
  'abbvie': 'ABBV',
  'adidas': 'ADDYY',
  'affirm': 'AFRM',
  'airbnb': 'ABNB',
  'airbus': 'EADSY',
  'akamai': 'AKAM',
  'altria': 'MO',
  'amazon': 'AMZN',
  'ameren': 'AEE',
  'ametek': 'AME',
  'apache': 'APA',
  'apollo': 'APO',
  'arhaus': 'ARHS',
  'arista': 'ANET',
  'biogen': 'BIIB',
  'boeing': 'BA',
  'chilis': 'EAT',
  'clorox': 'CLX',
  'con ed': 'ED',
  'corona': 'STZ',
  'cosmos': 'ATOM-USD',
  'costar': 'CSGP',
  'costco': 'COST',
  'crispr': 'CRSP',
  'darden': 'DRI',
  'diageo': 'DEO',
  'dick s': 'DKS',
  'disney': 'DIS',
  'ecolab': 'ECL',
  'editas': 'EDIT',
  'enovix': 'ENVX',
  'evergy': 'EVRG',
  'exelon': 'EXC',
  'fastly': 'FSLY',
  'fiserv': 'FISV',
  'fisker': 'FSR',
  'fiverr': 'FVRR',
  'gentex': 'GNTX',
  'gilead': 'GILD',
  'google': 'GOOG',
  'hermes': 'HESAY',
  'hilton': 'HLT',
  'hormel': 'HRL',
  'hp inc': 'HPQ',
  'humana': 'HUM',
  'incyte': 'INCY',
  'intuit': 'INTU',
  'jd com': 'JD',
  'kohl s': 'KSS',
  'kratos': 'KTOS',
  'kroger': 'KR',
  'lilium': 'LILM',
  'lowe s': 'LOW',
  'macy s': 'M',
  'micron': 'MU',
  'modelo': 'STZ',
  'moodys': 'MCO',
  'nasdaq': 'QQQ',
  'nikola': 'NKLA',
  'nubank': 'NU',
  'nvidia': 'NVDA',
  'ollies': 'OLLI',
  'onsemi': 'ON',
  'oracle': 'ORCL',
  'orange': 'ORAN',
  'ouster': 'OUST',
  'paccar': 'PCAR',
  'paypal': 'PYPL',
  'pfizer': 'PFE',
  'qualys': 'QLYS',
  'rapid7': 'RPD',
  'reddit': 'RDDT',
  'redfin': 'RDFN',
  'ripple': 'XRP-USD',
  'rivian': 'RIVN',
  'roblox': 'RBLX',
  's p500': 'SPY',
  'sanofi': 'SNY',
  'schwab': 'SCHW',
  'seagen': 'SGEN',
  'sirius': 'SIRI',
  'solana': 'SOL-USD',
  'spirit': 'SAVE',
  'splunk': 'SPLK',
  'square': 'SQ',
  'sunrun': 'RUN',
  'takeda': 'TAK',
  'target': 'TGT',
  'tinder': 'MTCH',
  'truist': 'TFC',
  'twilio': 'TWLO',
  'uipath': 'PATH',
  'united': 'UAL',
  'upwork': 'UPWK',
  'vertex': 'VRTX',
  'vmware': 'VMW',
  'wendys': 'WEN',
  'x corp': 'X',
  'zillow': 'Z',
  'adobe': 'ADBE',
  'aflac': 'AFL',
  'amgen': 'AMGN',
  'ansys': 'ANSS',
  'apple': 'AAPL',
  'aptiv': 'APTV',
  'astra': 'ASTR',
  'baidu': 'BIDU',
  'big 5': 'BGFV',
  'block': 'SQ',
  'c3 ai': 'AI',
  'canoo': 'GOEV',
  'chase': 'JPM',
  'chewy': 'CHWY',
  'chubb': 'CB',
  'ciena': 'CIEN',
  'cigna': 'CI',
  'cisco': 'CSCO',
  'deere': 'DE',
  'delta': 'DAL',
  'devon': 'DVN',
  'dover': 'DOV',
  'eaton': 'ETN',
  'exxon': 'XOM',
  'hinge': 'MTCH',
  'hut 8': 'HUT',
  'hyatt': 'H',
  'intel': 'INTC',
  'ionis': 'IONS',
  'jfrog': 'FROG',
  'kayak': 'BKNG',
  'kohls': 'KSS',
  'lilly': 'LLY',
  'linde': 'LIN',
  'lowes': 'LOW',
  'lucid': 'LCID',
  'lumen': 'LUMN',
  'macys': 'M',
  'magna': 'MGA',
  'marsh': 'MMC',
  'matic': 'MATIC-USD',
  'merck': 'MRK',
  'moody': 'MCO',
  'pepsi': 'PEP',
  'qorvo': 'QRVO',
  'sands': 'LVS',
  'shell': 'SHEL',
  'simon': 'SPG',
  'sp500': 'SPY',
  'tegna': 'TGNA',
  'tesla': 'TSLA',
  'total': 'TTE',
  'tyson': 'TSN',
  'unity': 'U',
  'veeva': 'VEEV',
  'volta': 'VLTA',
  'vroom': 'VRM',
  'xpeng': 'XPEV',
  'xylem': 'XYL',
  'zynga': 'ZNGA',
  'amex': 'AXP',
  'at t': 'T',
  'atom': 'ATOM-USD',
  'avax': 'AVAX-USD',
  'bofa': 'BAC',
  'citi': 'C',
  'coke': 'KO',
  'dana': 'DAN',
  'djia': 'DIA',
  'doge': 'DOGE-USD',
  'evgo': 'EVgo',
  'ford': 'F',
  'hess': 'HES',
  'idex': 'IEX',
  'lear': 'LEA',
  'link': 'LINK-USD',
  'lvmh': 'LVMUY',
  'nike': 'NKE',
  'oreo': 'MDLZ',
  'pseg': 'PEG',
  'ss c': 'SSNC',
  'temu': 'PDD',
  'tide': 'PG',
  'tsmc': 'TSM',
  'vans': 'VFC',
  'visa': 'V',
  'xcel': 'XEL',
  'zoom': 'ZM',
  'ada': 'ADA-USD',
  'att': 'T',
  'btc': 'BTC-USD',
  'dot': 'DOT-USD',
  'dow': 'DIA',
  'eth': 'ETH-USD',
  'fpl': 'NEE',
  'gap': 'GPS',
  'hbo': 'WBD',
  'j j': 'JNJ',
  'kfc': 'YUM',
  'kla': 'KLAC',
  'lam': 'LRCX',
  'ltc': 'LTC-USD',
  'nbc': 'CMCSA',
  'nxp': 'NXPI',
  'p g': 'PG',
  'sce': 'EIX',
  'sol': 'SOL-USD',
  'uni': 'UNI-USD',
  'xrp': 'XRP-USD',
};